import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, FileCheck2, Paperclip, PenLine, Save, Send, Sparkles, X } from 'lucide-react';
import { emailApi } from '../services/emailApi.js';
import { aiApi } from '../services/aiApi.js';
import { apiError } from '../services/api.js';
import { useToast } from '../components/Toast.jsx';

function parseRecipientList(value) { return value.split(/[;,\n]/).map((part) => part.trim()).filter(Boolean).map((entry) => { const match = entry.match(/^(.*?)\s*<([^>]+)>$/); return match ? { name: match[1].replace(/^"|"$/g, '').trim(), email: match[2].trim() } : { name: '', email: entry }; }); }
const commaRecipients = (list = []) => list.map((person) => person.name ? `${person.name} <${person.email}>` : person.email).join(', ');
export function ComposePage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const toast = useToast();
  const draftId = params.get('draftId'); const replyTo = params.get('replyTo'); const queryKey = useMemo(() => `${draftId || ''}:${replyTo || ''}`, [draftId, replyTo]);
  const [form, setForm] = useState({ to: '', cc: '', bcc: '', subject: '', bodyText: '' }); const [files, setFiles] = useState([]); const [oldFiles, setOldFiles] = useState([]); const [removeExistingAttachments, setRemoveExistingAttachments] = useState(false); const [replyThread, setReplyThread] = useState(''); const [inReplyTo, setInReplyTo] = useState(''); const [references, setReferences] = useState(''); const [aiGenerated, setAiGenerated] = useState(false); const [lastAiAction, setLastAiAction] = useState('NONE');
  const [loading, setLoading] = useState(Boolean(draftId || replyTo)); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [writerPrompt, setWriterPrompt] = useState(''); const [rewriteMode, setRewriteMode] = useState('PROFESSIONAL'); const [checkResult, setCheckResult] = useState(null);
  useEffect(() => {
    let live = true;
    const load = async () => { setLoading(Boolean(draftId || replyTo)); setError(''); setOldFiles([]); setFiles([]); setRemoveExistingAttachments(false); setReplyThread(''); setInReplyTo(''); setReferences('');
      try {
        if (draftId) { const data = await emailApi.drafts(); const draft = data.items?.find((item) => String(item._id) === draftId); if (!draft) throw new Error('Draft was not found.'); if (live) { setForm({ to: commaRecipients(draft.to), cc: commaRecipients(draft.cc), bcc: commaRecipients(draft.bcc), subject: draft.subject || '', bodyText: draft.bodyText || '' }); setOldFiles(draft.attachments || []); setReplyThread(draft.threadId || ''); setInReplyTo(draft.inReplyTo || ''); setReferences(draft.references || ''); setAiGenerated(Boolean(draft.aiGenerated)); setLastAiAction(draft.lastAiAction || 'NONE'); } }
        else if (replyTo) { const message = await emailApi.get(replyTo); if (live) { setForm({ to: commaRecipients(message.sender?.email ? [message.sender] : []), cc: '', bcc: '', subject: /^re:/i.test(message.subject || '') ? message.subject : `Re: ${message.subject || ''}`, bodyText: '', }); setReplyThread(message.threadId); setInReplyTo(message.messageIdHeader || ''); setReferences([message.references, message.messageIdHeader].filter(Boolean).join(' ').slice(0, 4000)); } }
      } catch (e) { if (live) setError(apiError(e)); } finally { if (live) setLoading(false); }
    };
    load(); return () => { live = false; };
  }, [queryKey]);
  const change = (key) => (event) => { setForm((value) => ({ ...value, [key]: event.target.value })); setCheckResult(null); };
  const appendFiles = (event) => { const next = Array.from(event.target.files || []); setFiles((current) => [...current, ...next].slice(0, 5)); event.target.value = ''; };
  const withBusy = async (name, action) => { setError(''); setBusy(name); try { return await action(); } catch (e) { setError(apiError(e)); return null; } finally { setBusy(''); } };
  const formPayload = () => ({ to: parseRecipientList(form.to), cc: parseRecipientList(form.cc), bcc: parseRecipientList(form.bcc), subject: form.subject, bodyText: form.bodyText, ...(draftId ? { draftId } : {}), ...(replyThread ? { threadId: replyThread } : {}), inReplyTo, references, aiGenerated, removeExistingAttachments, lastAiAction });
  const toFormData = () => { const data = new FormData(); const value = formPayload(); Object.entries(value).forEach(([key, item]) => data.append(key, ['to','cc','bcc'].includes(key) ? JSON.stringify(item) : String(item))); files.forEach((file) => data.append('attachments', file)); return data; };
  const save = async () => withBusy('save', async () => { const result = await emailApi.saveDraft(toFormData()); toast('Draft saved to Gmail.'); if (!draftId && result.draftId) navigate(`/compose?draftId=${result.draftId}`, { replace: true }); return result; });
  const send = async () => { const recipients = parseRecipientList(form.to); if (!recipients.length) { setError('Add at least one valid To recipient before sending.'); return; } if (!window.confirm(`Send this message to ${recipients.map((person) => person.email).join(', ')}?`)) return; await withBusy('send', async () => { await emailApi.send(toFormData()); toast('Message sent.'); navigate('/sent'); }); };
  const write = async () => { if (!writerPrompt.trim()) { setError('Describe the email you want to write first.'); return; } await withBusy('write', async () => { const result = await aiApi.write({ instruction: writerPrompt, subjectHint: form.subject }); setForm((value) => ({ ...value, subject: value.subject || result.subject, bodyText: result.bodyText })); setAiGenerated(true); setLastAiAction('WRITE'); setCheckResult(null); toast('Draft suggestion added. Review and edit it before sending.'); }); };
  const replySuggestion = async () => { if (!replyTo) { setError('Open a message first to generate a reply.'); return; } await withBusy('reply', async () => { const result = await aiApi.reply({ emailId: replyTo }); setForm((value) => ({ ...value, subject: value.subject || result.subject, bodyText: result.bodyText })); setAiGenerated(true); setLastAiAction('REPLY'); setCheckResult(null); toast('Reply suggestion added. Review and edit it before sending.'); }); };
  const rewrite = async () => { if (!form.bodyText.trim()) { setError('Add some message text to rewrite.'); return; } await withBusy('rewrite', async () => { const result = await aiApi.rewrite({ text: form.bodyText, mode: rewriteMode }); setForm((value) => ({ ...value, bodyText: result.rewrittenText })); setAiGenerated(true); setLastAiAction('REWRITE'); setCheckResult(null); toast('Rewrite suggestion applied. Review the edits.'); }); };
  const check = async () => withBusy('check', async () => { const result = await aiApi.check({ to: parseRecipientList(form.to), cc: parseRecipientList(form.cc), bcc: parseRecipientList(form.bcc), subject: form.subject, bodyText: form.bodyText, attachments: [...(removeExistingAttachments ? [] : oldFiles).map(({ filename, mimeType, size }) => ({ filename, mimeType, size })), ...files.map((file) => ({ filename: file.name, mimeType: file.type, size: file.size }))] }); setCheckResult(result); return result; });
  if (loading) return <div className="page"><div className="detail-loading card"><i className="skeleton"/><i className="skeleton"/><i className="skeleton"/></div></div>;
  return <div className="page compose-page"><div className="page-heading"><div><div className="eyebrow">MAILBOX</div><h1>{replyTo ? 'Reply to message' : draftId ? 'Edit draft' : 'New message'}</h1><p>Write a message and review it before sending.</p></div><div className="heading-actions"><button className="btn" onClick={save} disabled={!!busy}><Save size={15}/><span className="button-label">{busy === 'save' ? 'Saving…' : 'Save draft'}</span></button><button className="btn primary" onClick={send} disabled={!!busy}><Send size={15}/><span className="button-label">{busy === 'send' ? 'Sending…' : 'Send'}</span></button></div></div>
    {error && <div className="notice error" role="alert">{error}</div>}
    <div className="compose-grid"><section className="card compose-card"><div className="compose-fields"><div className="compose-field"><label htmlFor="to">To</label><input id="to" value={form.to} onChange={change('to')} placeholder="name@example.com" autoComplete="off" /></div><div className="compose-field"><label htmlFor="cc">Cc</label><input id="cc" value={form.cc} onChange={change('cc')} placeholder="Optional recipients" autoComplete="off" /></div><div className="compose-field"><label htmlFor="bcc">Bcc</label><input id="bcc" value={form.bcc} onChange={change('bcc')} placeholder="Optional recipients" autoComplete="off" /></div><div className="compose-field subject-field"><label htmlFor="subject">Subject</label><input id="subject" value={form.subject} onChange={change('subject')} placeholder="Subject" maxLength={998}/></div></div><textarea className="compose-body" value={form.bodyText} onChange={change('bodyText')} placeholder="Write your message…" aria-label="Message body" maxLength={100000}/><div className="compose-footer"><label className="btn small attach-button"><Paperclip size={14}/> Attach files<input type="file" multiple hidden onChange={appendFiles} /></label><span className="attachment-hint">Up to 5 files, 10 MB each</span><span className="compose-footer-spacer"/><span className="muted compose-saved-state">{aiGenerated && <><Sparkles size={13}/> AI assisted · review before sending</>}</span><button className="btn small" onClick={save} disabled={!!busy}><Save size={14}/> Save draft</button><button className="btn primary small" onClick={send} disabled={!!busy}><Send size={14}/> Send</button></div>
      {(oldFiles.length > 0 || files.length > 0) && <div className="selected-files">{oldFiles.map((file) => <div className={`file-chip ${removeExistingAttachments ? '' : 'old'}`} key={`old-${file.filename}`}><Paperclip size={13}/><span>{file.filename} {removeExistingAttachments ? '(will remove)' : '(existing)'}</span></div>)}{oldFiles.length > 0 && <button className="text-button remove-originals" onClick={() => setRemoveExistingAttachments((value) => !value)}>{removeExistingAttachments ? 'Keep existing attachments' : 'Remove existing attachments'}</button>}{files.map((file,index) => <div className="file-chip" key={`${file.name}-${index}`}><Paperclip size={13}/><span>{file.name}</span><button className="icon-button" onClick={() => setFiles((current) => current.filter((_,i) => i !== index))} aria-label={`Remove ${file.name}`}><X size={13}/></button></div>)}</div>}
    </section><aside className="compose-tools"><section className="card ai-tool-card"><div className="ai-tool-title"><span className="ai-tool-icon"><Sparkles size={15}/></span><div><b>AI writing assistant</b><small>Suggestions stay editable</small></div></div><label className="field ai-prompt"><span>Describe what you want to write</span><textarea rows="3" value={writerPrompt} onChange={(e) => setWriterPrompt(e.target.value)} placeholder="e.g. Ask Jordan to send the updated project timeline by Friday." /></label><button className="btn primary small full-button" disabled={!!busy} onClick={write}><PenLine size={14}/>{busy === 'write' ? 'Writing…' : 'Write with AI'}</button>{replyTo && <button className="btn small full-button" disabled={!!busy} onClick={replySuggestion}><Sparkles size={14}/>{busy === 'reply' ? 'Drafting reply…' : 'Suggest a reply'}</button>}<div className="tool-divider"/><label className="field"><span>Rewrite tone</span><select value={rewriteMode} onChange={(e) => setRewriteMode(e.target.value)}>{[['PROFESSIONAL','Professional'],['FRIENDLY','Friendly'],['CONCISE','Concise'],['FORMAL','Formal'],['CLARITY','Clearer'],['GRAMMAR','Grammar']].map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><button className="btn small full-button" disabled={!!busy} onClick={rewrite}><Sparkles size={14}/>{busy === 'rewrite' ? 'Rewriting…' : 'Rewrite message'}</button></section><section className="card check-card"><div className="ai-tool-title"><span className="ai-tool-icon mint"><FileCheck2 size={15}/></span><div><b>AI Check</b><small>Review common issues before sending</small></div></div><button className="btn small full-button" disabled={!!busy} onClick={check}><FileCheck2 size={14}/>{busy === 'check' ? 'Checking…' : 'Check this email'}</button>{checkResult && <div className="check-results"><div className={`check-overall ${checkResult.suggestions?.length ? 'attention' : ''}`}><CheckCircle2 size={15}/>{checkResult.suggestions?.length ? 'Review recommended' : 'Ready for your review'}</div>{checkResult.checklist?.map((item) => <div className="check-item" key={item.key}><span>{item.label}</span><b className={item.status === 'WARNING' ? 'warn' : 'pass'}>{item.status}</b>{item.issues?.length > 0 && <small>{item.issues.join(' ')}</small>}</div>)}<small className="check-disclaimer">{checkResult.disclaimer}</small></div>}</section><p className="compose-notice">AI suggestions may be inaccurate. Review recipients and content before sending.</p></aside></div>
  </div>;
}
