import { useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { ExternalLink, LogOut, Mail, Save, ShieldCheck, SlidersHorizontal, Sparkles, Unplug } from 'lucide-react';
import { settingsApi } from '../services/settingsApi.js';
import { logoutUser } from '../store/authSlice.js';
import { clearNotifications } from '../store/notificationSlice.js';
import { apiError } from '../services/api.js';
import { watchTheme } from '../services/theme.js';
import { useToast } from '../components/Toast.jsx';

const defaults = { replyTone: 'professional', writerTone: 'professional', theme: 'light', notifications: { newEmail: true, priority: true, meeting: true, phishing: true }, aiFeatures: { priorityDetection: true, meetingDetection: true, phishingDetection: true } };
const normalizePreferences = (value = {}) => ({
  replyTone: value.replyTone || defaults.replyTone,
  writerTone: value.writerTone || defaults.writerTone,
  theme: value.theme || defaults.theme,
  notifications: { ...defaults.notifications, ...value.notifications },
  aiFeatures: { ...defaults.aiFeatures, ...value.aiFeatures }
});
export function SettingsPage() {
  const dispatch = useDispatch(); const navigate = useNavigate();
  const [status, setStatus] = useState(null); const [prefs, setPrefs] = useState(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [connecting, setConnecting] = useState(false); const [disconnecting, setDisconnecting] = useState(false); const [error, setError] = useState(''); const toast = useToast();
  const load = async () => { setLoading(true); setError(''); try { const [gmail, result] = await Promise.all([settingsApi.gmailStatus(), settingsApi.getPreferences()]); setStatus(gmail); setPrefs(normalizePreferences(result.preferences)); } catch (e) { setError(apiError(e)); } finally { setLoading(false); } };
  useEffect(() => { load(); const result = new URLSearchParams(window.location.search).get('gmail'); if (result === 'connected') toast('Gmail connected successfully.'); else if (result === 'failed') toast('Gmail connection could not be completed.', 'error'); else if (result === 'cancelled') toast('Gmail connection was cancelled.', 'info'); if (result) window.history.replaceState({}, '', window.location.pathname); }, []);
  useEffect(() => { if (!loading) return watchTheme(prefs.theme); }, [prefs.theme, loading]);
  const patch = (key, value) => setPrefs((current) => ({ ...current, [key]: value }));
  const patchNested = (group, key, value) => setPrefs((current) => ({ ...current, [group]: { ...current[group], [key]: value } }));
  const save = async () => { setSaving(true); setError(''); try { const data = await settingsApi.updatePreferences(normalizePreferences(prefs)); setPrefs(normalizePreferences(data.preferences)); toast('Settings saved.'); } catch (e) { setError(apiError(e)); } finally { setSaving(false); } };
  const connect = async () => { setConnecting(true); setError(''); try { const { authorizationUrl } = await settingsApi.connectGmail(); window.location.assign(authorizationUrl); } catch (e) { setError(apiError(e, 'Could not start Gmail authorization.')); setConnecting(false); } };
  const disconnect = async () => { if (!window.confirm('Disconnect Gmail and remove the locally synchronized messages and drafts from SmartMail?')) return; setDisconnecting(true); try { await settingsApi.disconnectGmail(); setStatus({ connected: false }); toast('Gmail disconnected.'); } catch (e) { toast(apiError(e), 'error'); } finally { setDisconnecting(false); } };
  const signOut = async () => { try { await dispatch(logoutUser()).unwrap(); dispatch(clearNotifications()); navigate('/login'); } catch (e) { toast(apiError(e), 'error'); } };
  if (loading) return <div className="page"><div className="detail-loading card"><i className="skeleton"/><i className="skeleton"/><i className="skeleton"/></div></div>;
  return <div className="page settings-page"><div className="page-heading"><div><div className="eyebrow">PREFERENCES</div><h1>Settings</h1><p>Manage your connected mailbox and SmartMail experience.</p></div><button className="btn primary" onClick={save} disabled={saving}><Save size={15}/><span className="button-label">{saving ? 'Saving…' : 'Save changes'}</span></button></div>{error && <div className="notice error" role="alert">{error}</div>}
    <section className="settings-section"><div className="section-intro"><div className="settings-icon"><Mail size={18}/></div><div><h2>Connected account</h2><p>Gmail access is used to sync and send messages you choose.</p></div></div><div className="card settings-card connected-account"><div className="gmail-symbol">G</div><div className="account-copy"><b>{status?.connected ? status.email : 'No Gmail account connected'}</b><small>{status?.connected ? <>Connected{status.lastSyncedAt ? ` · Last synced ${new Date(status.lastSyncedAt).toLocaleString()}` : ''}</> : 'Connect Gmail to sync your mailbox and send email.'}</small></div>{status?.connected ? <><span className="connection-status"><i/> Connected</span>{!status.mailboxAccessGranted && <button className="btn primary small" onClick={connect} disabled={connecting || !status.oauthConfigured}>{connecting ? 'Reconnecting…' : 'Grant Gmail access'} <ExternalLink size={13}/></button>}<button className="btn small" onClick={disconnect} disabled={disconnecting}><Unplug size={14}/>{disconnecting ? 'Disconnecting…' : 'Disconnect'}</button></> : <button className="btn primary small" onClick={connect} disabled={connecting || !status?.oauthConfigured}>{connecting ? 'Connecting…' : 'Connect Gmail'} <ExternalLink size={13}/></button>}</div>{status?.connected && !status.mailboxAccessGranted && <p className="settings-helper"><ShieldCheck size={14}/> Gmail is connected, but mailbox access was not granted. Reconnect and approve the requested Gmail permissions; this keeps locally synced mail.</p>}{!status?.connected && !status?.oauthConfigured && <p className="settings-helper"><ShieldCheck size={14}/> Gmail OAuth is not configured. Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in server/.env, then restart the API.</p>}<p className="settings-helper"><ShieldCheck size={14}/> SmartMail requests Gmail permissions for email read, draft, and send functionality. Disconnecting removes local mailbox data.</p></section>
    <section className="settings-section"><div className="section-intro"><div className="settings-icon lilac"><SlidersHorizontal size={18}/></div><div><h2>Writing preferences</h2><p>Set the starting tone for AI generated messages.</p></div></div><div className="card settings-card settings-fields"><label className="field"><span>Reply tone</span><select value={prefs.replyTone} onChange={(e) => patch('replyTone', e.target.value)}>{['professional','friendly','formal','concise'].map((tone) => <option key={tone} value={tone}>{tone[0].toUpperCase()+tone.slice(1)}</option>)}</select></label><label className="field"><span>Writing tone</span><select value={prefs.writerTone} onChange={(e) => patch('writerTone', e.target.value)}>{['professional','friendly','formal','concise'].map((tone) => <option key={tone} value={tone}>{tone[0].toUpperCase()+tone.slice(1)}</option>)}</select></label><label className="field"><span>Appearance</span><select value={prefs.theme} onChange={(e) => patch('theme', e.target.value)}><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label></div></section>
    <section className="settings-section"><div className="section-intro"><div className="settings-icon mint"><Sparkles size={18}/></div><div><h2>AI and notifications</h2><p>Choose which inbox insights and alerts are enabled.</p></div></div><div className="card settings-card toggle-settings"><h3>AI insights</h3><Toggle label="Priority detection" description="Identify messages that may need a timely response." checked={prefs.aiFeatures.priorityDetection} onChange={(value) => patchNested('aiFeatures','priorityDetection',value)}/><Toggle label="Meeting detection" description="Extract meeting dates and details from messages." checked={prefs.aiFeatures.meetingDetection} onChange={(value) => patchNested('aiFeatures','meetingDetection',value)}/><Toggle label="Security review" description="Flag messages with signs of possible phishing." checked={prefs.aiFeatures.phishingDetection} onChange={(value) => patchNested('aiFeatures','phishingDetection',value)}/><div className="settings-divider"/><h3>Notifications</h3><Toggle label="New email alerts" checked={prefs.notifications.newEmail} onChange={(value) => patchNested('notifications','newEmail',value)}/><Toggle label="Priority alerts" checked={prefs.notifications.priority} onChange={(value) => patchNested('notifications','priority',value)}/><Toggle label="Meeting alerts" checked={prefs.notifications.meeting} onChange={(value) => patchNested('notifications','meeting',value)}/><Toggle label="Security alerts" checked={prefs.notifications.phishing} onChange={(value) => patchNested('notifications','phishing',value)}/></div></section>
    <section className="settings-section account-settings"><div className="section-intro"><div className="settings-icon"><ShieldCheck size={18}/></div><div><h2>Account</h2><p>End your current SmartMail session on this device.</p></div></div><div className="card settings-card account-session"><div><b>Signed in</b><small>Your session cookie is protected and can be revoked by signing out.</small></div><button className="btn small" onClick={signOut}><LogOut size={14}/> Sign out</button></div></section>
    <div className="settings-bottom"><span>Preferences are saved to your account.</span><button className="btn primary" onClick={save} disabled={saving}><Save size={15}/>{saving ? 'Saving…' : 'Save changes'}</button></div>
  </div>;
}
function Toggle({ label, description, checked, onChange }) { return <label className="toggle-row"><span><b>{label}</b>{description && <small>{description}</small>}</span><input type="checkbox" checked={Boolean(checked)} onChange={(event) => onChange(event.target.checked)} /><span className="toggle-track" aria-hidden="true"><i/></span></label>; }
